### ISSUE TITLE
 最初から進めません。

### ISSUE THREAD

**Issue by Mike-JH0912** [misshie/ngsdat2#10]
Mac OS Catalinaを買い、本書を読んで勉強を始めています。
本書のP64を参考にしたのですが、最初から躓いています。
ngsdt2-master の解凍まではうまくいきました

(basse) MacBook-Pro ~ % cd ~
(base) MacBook-Pro ~ % mkdir -p Analysis
(base) MacBook-Pro ~ % cd Analysis
(base) MacBook-Pro Analysis % unzip ~/Downloads/ngsdat2-master.zip

 中略
(base) MacBook-Pro Analysis % cd ngsdat2-master
(base) MacBook-Pro ngsdat2-master % less 010_download-ucsc.sh

ここで以下のメッセージが出て先に進めません。
周りに聞ける人がいないので、どうしたらよいか教えて下さい。

010_download-ucsc.sh: No such file or directory
(base) MacBook-Pro ngsdat2-master %

**Comment by misshie** [comment]
ご迷惑おかけしています。確認してみます。もう少々お時間下さい。

**Comment by Mike-JH0912** [comment]
Mishima先生

初めまして、順天堂大学の平井です。
初学者のため、ご迷惑をおかけします。
昨夜、該当ファイル010、、、を開いてコピペしたところ、うまく先に進めましたことを
ご報告いたします。遅くなり申し訳ございません。
しかし、テキストに書いてある通りに行っても先に進めませんでしたので、
原因をお教えいただけますと助かります。

よろしくお願いいたします。

平井





2020年5月15日(金) 10:23 MISHIMA, Hiroyuki <notifications@github.com>:

**Comment by Mike-JH0912** [comment]
010_download-ucsc.sh のファイルを開けて、内容をコピペしたところ、先に進めました。
このステップ以降も、やはりテキスト通りにやるとスタックします。
各ステップのファイルを開けてコピペしたら進めました。
